package org.skyfw.base.mcodes;

public enum TBaseMCodeFamily {
      INFORMATIONAL_CODE__FAMILY
    , SUCCESS_CODE_FAMILY
    , CONNECTION_ERROR_CODE_FAMILY
    , CLIENT_ERROR_CODE_FAMILY
    , SERVER_ERROR_CODE_FAMILY
    , LOCAL_ERROR_CODE_FAMILY
    , UNKNOWN_ERROR_CODE_FAMILY;

}
